# .NET5.0
# Build and test .NET5.0 projects.
# Compilation for releasing to Prep/Prod in Optimizely DXP

trigger: none
pr: none
name: $(Version.Major).$(Version.Minor).$(Version.Patch).$(Build.BuildId)
resources:
  repositories:
  - repository: self
    type: git
    ref: develop
variables:
 - group: CMS12-Perficient.Accelerator.Web.Version
 - group: CMS12-Perficient.Accelerator.Web.DxpApi 
stages:
- stage: ProductionToPreproduction
  displayName: 'ProductionToPreproduction'
  jobs:
   - template: content-template.yml
     parameters:
       SOURCE: Production
       TARGET: Preproduction
- stage: PreproductionToIntegration
  dependsOn: ProductionToPreproduction
  condition: succeeded('ProductionToPreproduction')
  displayName: 'Preproduction To Integration'
  jobs:
   - template: content-template.yml
     parameters:
       SOURCE: Preproduction
       TARGET: Integration